language : node_js
node_js : "stable"
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script : karma start karma.conf.js

after_script: cat coverage/**/*lcov.info | ./node_modules/.bin/coveralls

